name: stars_streamlit
channels:
  - conda-forge
dependencies:
  - matplotlib=3.10.8
  - numpy=2.4.2
  - pandas=2.3.3
  - pip=26.0.1
  - plotly=6.5.2
  - python=3.12
  - scipy=1.16.3
  - simpy=4.1.1
  - streamlit=1.54.0
  - pip:
    - treat-sim==3.0.0
