name: stars_streamlit
channels:
  - conda-forge
dependencies:
  - bokeh=2.4.3
  - matplotlib=3.7.1
  - numpy=1.25.0
  - pandas=2.0.2
  - pip=21.0.1
  - plotly=5.21.0
  - python=3.10.13
  - scipy=1.10.1
  - simpy=4.1.1
  - pip:
    - streamlit==1.33.0
    - streamlit-bokeh-events==0.1.2
